[email]
sender = "your_email@gmail.com"
password = "your_app_password"

[firebase]
config = '''
{
  "type": "service_account",
  "project_id": "...",
  "private_key_id": "...",
  "private_key": "...",
  "client_email": "...",
  "client_id": "...",
  "auth_uri": "...",
  "token_uri": "...",
  "auth_provider_x509_cert_url": "...",
  "client_x509_cert_url": "..."
}
'''
storage_bucket = "your-bucket-name.appspot.com"

[app]
professor_secret_key = "your_secret_key_here"
